steps:
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - -f
  - Dockerfile.swimming
  - -t
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_IMAGE_NAME}:${_TAG}
  - .

images:
- ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_IMAGE_NAME}:${_TAG}
